"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.constants = void 0;
exports.constants = {
    NULL: null,
    FALSE: false,
    TRUE: true,
    ZERO: 0,
    MINUS_ONE: -1,
    ARRAY: [],
    OBJECT: {},
    SPAN_MATCH: '</?span[^>]*>',
    AR_REGEX_PATTERN: /[\u0600-\u06FF\u0750-\u077F]/,
    PERSIAN_NUMBERS: ['۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹', '۰'],
    ARABIC_NUMBERS: ['١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩', '٠'],
    ENGLISH_NUMBERS: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
    SUCCESS_CODE: 200,
    ERROR_CODE: 500,
    WRITE_SUCCESS_CODE: 201,
    UNAUTH_CODE: 401,
    NOTFOUND_CODE: 404,
    AR: 'ar',
    EN: 'en',
    threshold: 0.79,
    literal_factor: 1.1,
    pct_factor: 0.9,
    EQUAL: 'equal',
    ANY: 'any',
    BETWEEN: 'between',
    GREATER: 'greater',
    GREATER_EQUAL: 'greater-equal',
    BELOW: 'below',
    NOT_EQUAL: 'not-equal',
    BELOW_EQUAL: 'below-equal',
    DATETIME_METRICS: ['day', 'week', 'month', 'quarter', 'year'],
    CURRENT_YEAR: 'CURRENT_YEAR',
    PREVIOUS_YEAR: 'PREVIOUS_YEAR',
    CURRENT_QUARTER: 'CURRENT_QUARTER',
    PREVIOUS_QUARTER: 'PREVIOUS_QUARTER',
    CURRENT_MONTH: 'CURRENT_MONTH',
    NEXT_MONTH: 'NEXT_MONTH',
    PREVIOUS_MONTH: 'PREVIOUS_MONTH',
    CURRENT_WEEK: 'CURRENT_WEEK',
    PREVIOUS_WEEK: 'PREVIOUS_WEEK',
    PREVIOUS_TWO_DAY: 'PREVIOUS_TWO_DAY',
    CURRENT_DAY: 'CURRENT_DAY',
    PREVIOUS_DAY: 'PREVIOUS_DAY',
    OBJECT_TYPE: 'object',
    ARRAY_TYPE: 'array',
    STRING_TYPE: 'string',
    NUMBER_TYPE: 'number',
    BOOL_TYPE: 'boolean',
    CONTENT_TYPE: 'Content-Type',
    APPLICATION_JSON: 'application/json; charset=utf-8',
    OBLIGATION_REQUIRED: 'required',
    OBLIGATION_OPTIONAL: 'optional',
    NUMBER_ENTITY: 'number_entity',
    FIXED_LIST1: 'fixed_list1',
    FIXED_LIST2: 'fixed_list2',
    FIXED_LIST3: 'fixed_list3',
    TAG_ENTITY1: 'tag_entity1',
    TAG_ENTITY2: 'tag_entity2',
    TAG_ENTITY3: 'tag_entity3',
    HIGH_PRIORITY: 'high',
    NOTIFICATION_CLICK: 'FLUTTER_NOTIFICATION_CLICK',
    API_PREFIX: '/api',
    CARD_QUERY_TABLE: 'table',
    CARD_QUERY_HEADER: 'header',
    REGISTRY_TYPE_PREDICTIVE: 'predictive',
    REGISTRY_TYPE_COMMON: 'common',
    REGISTRY_TYPE_ATTACHMENT: 'attachment',
};
exports.default = exports.constants;
